name: 'Daily Job'

on:
  schedule:
    - cron: '0 20 * * *' # UTC
  workflow_dispatch:

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取所有历史记录而不是单次提交

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencc-python-reimplemented

      - name: Run Python script
        run: python main.py

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github_actions[bot]"
          git add live.txt live.m3u
          # 检查是否有更改需要提交
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m ":tada: AutoUpdate $(date +'%Y%m%d')"
          fi

      - name: Pull and rebase
        run: |
          git pull origin main --rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}