name: Run Script

on:
  schedule:
    - cron: '0 20 * * *'  # 每天UTC时间0点运行（北京时间8点）
  workflow_dispatch:  # 允许手动触发

jobs:
  run_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: cloudplains/jnsj
        token: ${{ secrets.GITHUB_TOKEN }}
        ssh-strict: true
        persist-credentials: true
        clean: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencc-python-reimplemented

    - name: Run main.py
      run: python main.py

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions[bot]"
        git add tv202303.txt tv202303.m3u
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m ":rocket: AutoUpdate $(date +'%Y%m%d')"
          git pull origin main --rebase
          git push origin main
        fi