name: 'Daily Job'

on:
  schedule:
    - cron: '0 20 * * *' # UTC
  workflow_dispatch:

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencc-python-reimplemented

      - name: Clean URLs
        run: python main.py --clean-urls

      - name: Run Python script
        run: python main.py

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github_actions[bot]"
          git add live.txt live.m3u others.txt assets/urls.txt
          git commit -m ":tada:  AutoUpdate $(date +'%Y%m%d')"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}