name: Sync IPTV0905 File

on:
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 时间 3:00 (北京时间 11:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 镜像 :cite[1]:cite[2]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 更新到最新稳定版 :cite[4]

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp requests eventlet

    - name: Run IPTV script
      run: |
        python iptv0905.py

    - name: Upload iptv0905.txt artifact
      uses: actions/upload-artifact@v4  # 更新到 v4 版本 :cite[4]:cite[9]
      with:
        name: iptv0905-result
        path: iptv0905.txt
        retention-days: 7  # 可选：设置产物保留时间