name: Sync External Releases

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行一次

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许创建发布和上传资源
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run sync script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python sync_releases.py --repo Guovin/iptv-api --dest-dir ./downloads

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag_name: synced-${{ github.run_id }}
        name: Synced Releases (${{ github.run_id }})
        body: |
          自动同步的外部Release资源
          同步时间: ${{ github.run_created }}
          源仓库: Guovin/iptv-api
        draft: false
        prerelease: false
        makeLatest: "false"

    - name: Upload Release Assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./downloads/*.zip"
        artifactContentType: "application/zip"
        tag: synced-${{ github.run_id }}
        allowUpdates: true
        replacesArtifacts: true