name: Update IPTV Live Sources

on:
  schedule:
    - cron: '0 16 * * *'  # 每天UTC时间16点运行（对应北京时间0点）
  workflow_dispatch:  # 允许手动触发

jobs:
  update-iptv:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5小时超时

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp eventlet requests

    - name: Create assets directory if not exists
      run: mkdir -p assets

    - name: Run IPTV script
      run: python iptv.py

    - name: Merge with existing live.txt
      run: |
        # 如果已有live.txt，则合并新旧结果
        if [ -f "assets/live.txt" ]; then
          # 备份原文件
          cp assets/live.txt assets/live_backup.txt
          # 合并文件并去重
          cat itvlist.txt assets/live.txt | sort -u > assets/merged.txt
          mv assets/merged.txt assets/live.txt
          echo "Merged with existing live.txt"
        else
          # 第一次运行，直接移动文件
          mv itvlist.txt assets/live.txt
          echo "Created new live.txt"
        fi

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/live.txt
        git commit -m "Auto-update: IPTV live sources $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
        git push