name: Validate Live Sources

on:
  schedule:
    # 每周日凌晨2点运行（UTC时间，相当于北京时间上午10点）
    - cron: '0 2 * * 0'
  # 也允许手动触发
  workflow_dispatch:

jobs:
  validate-live:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 需要完全历史记录来比较更改
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies (if any)
      run: |
        # 如果有任何依赖需要安装，可以在这里添加
        # pip install requests
        echo "No additional dependencies needed"

    - name: Run validation script
      run: python validate_live.py

    - name: Check for changes
      id: check_changes
      run: |
        git diff --quiet assets/live.txt || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/live.txt
        git commit -m "Auto-update: Validate and update live sources $(date +'%Y-%m-%d %H:%M')"
        git push