- name: Commit changes
  run: |
    # 配置Git用户
    git config --local user.email "actions@github.com"
    git config --local user.name "github-actions[bot]"
    
    # 只添加特定文件
    git add tv202303.txt tv202303.m3u
    
    # 检查是否有变更
    if [ -z "$(git status --porcelain)" ]; then
      echo "没有变更需要提交"
    else
      # 获取最新变更
      git pull origin main --rebase --autostash
      
      # 提交变更
      git commit -m ":rocket: AutoUpdate $(date +'%Y%m%d')"
      
      # 重试推送（最多3次）
      for i in {1..3}; do
        git pull origin main --rebase
        if git push origin main; then
          echo "推送成功"
          break
        else
          echo "推送失败，重试 $i/3"
          sleep 5
        fi
      done
    fi