- name: Create and run validation script
  run: |
    cat << 'EOL' > validate_urls.py
import requests
import time
from datetime import datetime

def validate_urls():
    with open('urls.txt', 'r', encoding='utf-8') as f:
        urls = [line.strip() for line in f if line.strip()]
    
    print(f"Found {len(urls)} URLs to validate")
    
    valid_urls = []
    invalid_urls = []
    
    for i, url in enumerate(urls):
        try:
            print(f"Testing URL {i+1}/{len(urls)}: {url}")
            response = requests.get(url, timeout=10, allow_redirects=True)
            if response.status_code == 200:
                valid_urls.append(url)
                print(f"✓ Valid: {url}")
            else:
                invalid_urls.append(url)
                print(f"✗✗ Invalid (status {response.status_code}): {url}")
        except Exception as e:
            invalid_urls.append(url)
            print(f"✗✗ Error: {url} - {str(e)}")
        
        time.sleep(0.5)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_filename = f"urls_{timestamp}.txt"
    
    with open(backup_filename, 'w', encoding='utf-8') as f:
        for url in valid_urls:
            f.write(url + '\n')
    
    with open('urls.txt', 'w', encoding='utf-8') as f:
        for url in valid_urls:
            f.write(url + '\n')
    
    report = f"""URL Validation Report
Generated at: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Total URLs: {len(urls)}
Valid URLs: {len(valid_urls)}
Invalid URLs: {len(invalid_urls)}
Backup file: {backup_filename}
"""
    
    print(report)
    
    with open('url_validation_report.txt', 'w', encoding='utf-8') as f:
        f.write(report)
        if invalid_urls:
            f.write("\nInvalid URLs:\n")
            for url in invalid_urls:
                f.write(f"- {url}\n")

if __name__ == "__main__":
    validate_urls()
EOL
    python validate_urls.py