- name: Commit changes
  run: |
    # 配置Git用户
    git config --local user.email "actions@github.com"
    git config --local user.name "github-actions[bot]"
    
    # 获取当前分支名称
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    
    # 只添加特定文件
    git add tv202303.txt tv202303.m3u
    
    # 检查是否有变更
    if [ -z "$(git status --porcelain)" ]; then
      echo "没有变更需要提交"
      exit 0
    fi
    
    # 提交变更
    git commit -m ":rocket: AutoUpdate $(date +'%Y%m%d')"
    
    # 重试推送（最多3次）
    for i in {1..3}; do
      # 先拉取最新变更（不使用autostash）
      if ! git pull origin $CURRENT_BRANCH --rebase; then
        echo "拉取失败，尝试终止变基"
        git rebase --abort
        echo "重试拉取..."
        sleep 2
        continue
      fi
      
      # 尝试推送
      if git push origin $CURRENT_BRANCH; then
        echo "推送成功"
        break
      else
        echo "推送失败，重试 $i/3"
        sleep 5
      fi
    done
    
    # 如果所有重试都失败
    if [ $i -eq 3 ]; then
      echo "错误：推送失败3次，请手动处理"
      exit 1
    fi