name: URL Validation Workflow

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  validate_urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version:  '3.10'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Create and run validation script
      run: |
        cat > validate_urls.py << 'EOL'
import requests
import time
from datetime import datetime

def validate_urls():
    with open('urls.txt', 'r', encoding='utf-8') as f:
        urls = [line.strip() for line in f if line.strip()]
    
    print(f"Found {len(urls)} URLs to validate")
    
    valid_urls = []
    invalid_urls = []
    
    for i, url in enumerate(urls):
        try:
            print(f"Testing URL {i+1}/{len(urls)}: {url}")
            response = requests.get(url, timeout=10, allow_redirects=True)
            if response.status_code == 200:
                valid_urls.append(url)
                print(f"✓ Valid: {url}")
            else:
                invalid_urls.append(url)
                print(f"✗ Invalid (status {response.status_code}): {url}")
        except Exception as e:
            invalid_urls.append(url)
            print(f"✗ Error: {url} - {str(e)}")
        
        time.sleep(0.5)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_filename = f"urls_{timestamp}.txt"
    
    with open(backup_filename, 'w', encoding='utf-8') as f:
        for url in valid_urls:
            f.write(url + '\n')
    
    with open('urls.txt', 'w', encoding='utf-8') as f:
        for url in valid_urls:
            f.write(url + '\n')
    
    report = f"""URL Validation Report
Generated at: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Total URLs: {len(urls)}
Valid URLs: {len(valid_urls)}
Invalid URLs: {len(invalid_urls)}
Backup file: {backup_filename}
"""
    
    print(report)
    
    with open('url_validation_report.txt', 'w', encoding='utf-8') as f:
        f.write(report)
        if invalid_urls:
            f.write("\nInvalid URLs:\n")
            for url in invalid_urls:
                f.write(f"- {url}\n")

if __name__ == "__main__":
    validate_urls()
EOL

        python validate_urls.py

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "✅ URL validation - $(date +'%Y%m%d_%H%M%S')"
          git pull --rebase
          git push
        fi